Improve google usage
ReseauEntourage/entourage-webapp pull request #22
Opened 2020-11-16 09:10 UTC by loiclegoff

2020-11-16 20:55 UTC, GuillaumeJasmin requested changes

2020-11-16 20:55 UTC, GuillaumeJasmin commented on src/utils/misc/GoogleMaps.ts
> +      sessionToken: createAutocompleteSessionToken(),
On va créer qu'une seule instance par chargement, mais je pense qu'il faut une nouvelle instance par recherche non ? Je doute qu'on puisse réutiliser la session pendant 20 min par exemple coté Google
Voir ici: https://developers.google.com/places/web-service/session-tokens

2020-11-21 17:31 UTC, loiclegoff commented on src/utils/misc/GoogleMaps.ts
> +      sessionToken: createAutocompleteSessionToken(),
Je viens de mettre à jour le code pour recreer un token a chaque instanciation de GoogleMapLocation. Dis moi, ce que tu en penses.

2020-12-09 21:44 UTC, GuillaumeJasmin requested changes

2020-12-09 22:05 UTC, GuillaumeJasmin requested changes

2020-12-09 22:05 UTC, GuillaumeJasmin commented on src/pages/_document.tsx
> -          />
Il y a un problème avec le fait de supprimer le chargement du script sur tout le site: les formulaires lorsqu'on est sur la page `Messages` ne fonctionnent si on arrive directement sur la page (ou qu'on refresh).
Il faut donc pouvoir charger le script d'autocomplete même en dehors de la map.

Il faut peut-être voir pour charger le script directement avec le composant d'autocomplete

2020-12-12 09:43 UTC, loiclegoff commented on src/components/Map/Map.tsx
>    return (
Du coup GoogleMapReact ne le charge pas s'il trouve la deps déjà chargé ?

2020-12-12 22:47 UTC, GuillaumeJasmin commented on src/components/Map/Map.tsx
>    return (
Bonne question, j'ai retiré la clé d'API google map des props du composant, mais c'est vrai que je n'ai pas vérifié si c'était chargé deux fois

2020-12-15 20:53 UTC, GuillaumeJasmin commented on src/components/Map/Map.tsx
>    return (
Je viens de vérifier, pas de double chargement, donc c'est bon

2020-12-15 20:53 UTC, GuillaumeJasmin approved these changes

2020-12-16 14:30 UTC, GuillaumeJasmin approved these changes

2020-12-16 14:30 UTC, merged