:sparkles: feat(entourages): add the possibility to close an action a…
ReseauEntourage/entourage-webapp pull request #23
Opened 2020-12-02 23:11 UTC by loiclegoff

…nd reopen it

2020-12-08 22:52 UTC, GuillaumeJasmin requested changes

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/components/Modal/Modal.tsx
> +      {title ? (
Je pense qu'on devrait toujours avoir un titre en fait, pour que toutes les modals soient visuellement identiques.
Du coup je laisser comme avant, mais je renforcerai le typage TS en mettant le titre en required. Tu en penses quoi ?

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/components/Modal/Modal.tsx
> +            )}
Un peu difficile à lire, trop de ternaires imbriquées, il faut décomposer plus que ça pour avoir un DOM plus clean

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/containers/MapContainer/RightCards/Actions.styles.ts
> +  padding: 9px;
Pour les margins et padding, il faut utiliser les spacings

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/containers/MapContainer/RightCards/Actions.styles.ts
> +export const NoActionsSpan = styled.span`
Pas d'indication de balisage dans les noms des composants

```suggestion
export const NoActions = styled.span`
```

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/containers/MapContainer/RightCards/Actions.styles.ts
> +  font-size: 12px;
Il faut utiliser un style de texte déjà défini et éviter de mettre des font-size spécifique.

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/containers/ModalCloseAction/ModalCloseAction.styles.ts
> +  margin-top: 16px;
spacings ici aussi

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/containers/ModalCloseAction/ModalCloseAction.tsx
> +export function ModalCloseAction(props: ModalCloseAction) {
```suggestion
interface ModalCloseActionProps {
  id: number;
}

export function ModalCloseAction(props: ModalCloseActionProps) {
```

2020-12-08 22:52 UTC, GuillaumeJasmin commented on src/core/store/mutations/useMutateReopenEntourages.ts
> +type Data = { id: number; }
```suggestion
type Data = { entourageId: number; }
```

2020-12-09 13:47 UTC, loiclegoff commented on src/components/Modal/Modal.tsx
> +      {title ? (
Il y a quand même une lourdeur visuelle dans certain cas. Peut être validé ça avec vaïté ?

2020-12-14 18:59 UTC, loiclegoff commented
@GuillaumeJasmin, je me pose une question fonctionnelle du coup, est ce que je retire du feed l'action/event retiré...

2020-12-17 20:59 UTC, GuillaumeJasmin approved these changes

2020-12-17 21:12 UTC, merged