Last changes before public release
ReseauEntourage/entourage-webapp pull request #32
Opened 2021-01-14 16:59 UTC by emile-bex

2021-01-14 18:17 UTC, loiclegoff commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +      return <MoreHoriz {...getIconProps()} />
Si tu as créer une interface avec tout les catégories de displayCategorie, je recommande une map avec un `Record<DisplayCategories, JSX.Element>`. Ca permet d'éviter une oublie de certain cas. A voir si tu peux faussi faire ça pour l'entourageType

2021-01-14 18:59 UTC, GuillaumeJasmin requested changes

2021-01-14 18:59 UTC, GuillaumeJasmin commented on server.js
> +    server.listen(3000, (err) => {
T'es sur que c'est le port 3000 sur Heroku ? Pour moi il faut laisser la variable d'env dans le package.json

2021-01-14 18:59 UTC, GuillaumeJasmin commented on server.js
> +      console.log('> Ready on http://localhost:3000')
Là on log même pour la prod ?

2021-01-14 18:59 UTC, GuillaumeJasmin commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +    backgroundColor = colors.main.blue
Il faut éviter d'éditer une valeur en dehors du scope dans lequel elle est utilisée, ça complexifie la lecture.
Ici, `backgroundColor` devrait être gérée dans `getIconProps`.

D'ailleurs, pourquoi faire une fonction `getIconProps` et pas juste un objet `iconProps` ?

2021-01-14 18:59 UTC, GuillaumeJasmin commented on src/containers/Nav/NavNotificationBar.tsx
> +        href="https://entourage.social/app"
On devrait la mettre dans les contantes  `src/constants/index.ts`
```suggestion
        href={constants.LEGACY_WEB_APP_URL}
```

2021-01-14 18:59 UTC, GuillaumeJasmin commented on src/core/sentry/index.ts
> +      if (event?.exception?.values?.some(((error) => error.value === 'user-feedback'))) {
On peut rajouter un peu de contexte, car on détourne un peu le comportement

```suggestion
      const isUserFeedbackFromBanner = event?.exception?.values?.some(((error) => error.value === 'user-feedback'))

      if (isUserFeedbackFromBanner) {
```

2021-01-14 18:59 UTC, GuillaumeJasmin commented on src/i18n/fr.ts
> +      dialogLang: 'fr',
ça ne devrait être ici, normalement il nous faudrait une variable `locale` globale pour toute l'app, ça ne fait pas partie des textes afficher en interface

2021-01-14 19:10 UTC, emile-bex commented on server.js
> +      console.log('> Ready on http://localhost:3000')
Ouais ça log même pour la prod. Il ne faut pas ? Ca permet de savoir quand le serveur a bien démarré ou pas dans les logs non ?

2021-01-14 19:51 UTC, emile-bex commented on server.js
> +    server.listen(3000, (err) => {
Yes effectivement il faut utiliser `const port = process.env.PORT || 3000` parce Heroku le fix dans une variable d'environnement

2021-01-14 20:01 UTC, emile-bex commented on src/i18n/fr.ts
> +      dialogLang: 'fr',
Effectivement mais je me suis dis que dans un premier temps ça permettrait de gérer ça facilement s'il y avait besoin.

2021-01-15 13:52 UTC, emile-bex commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +      return <MoreHoriz {...getIconProps()} />
Je vais faire ça, merci !

2021-01-15 13:52 UTC, emile-bex commented on src/containers/Nav/NavNotificationBar.tsx
> +        href="https://entourage.social/app"
Je vais fixer ça 😉

2021-01-15 13:53 UTC, emile-bex commented on src/core/sentry/index.ts
> +      if (event?.exception?.values?.some(((error) => error.value === 'user-feedback'))) {
Effectivement, merci ! 😊

2021-01-15 13:59 UTC, emile-bex commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +    backgroundColor = colors.main.blue
L'idée de la fonction c'était de récupérer la valeur de `backgroundColor` comme on l'a fixé au moment de l'appel de la fonction. Si on fait un objet, on va garder la valeur de `backgroundColor` au moment de la création de l'objet. Alors que je le modifie potentiellement plus tard.

2021-01-15 14:01 UTC, emile-bex commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +    backgroundColor = colors.main.blue
Mais je peux faire en sorte de passer le `backgroundColor` en paramètre de la fonction `getIconProps` ce sera plus lisible comme ça

2021-01-19 21:49 UTC, GuillaumeJasmin requested changes

2021-01-19 21:49 UTC, GuillaumeJasmin commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +  }
Je trouve que c'est encore plus confus qu'avant, car le getIncon n'apport rien de plus puisqu'on fait toujours une mutation sur `iconBackgroundColor` .
Les mutations sont quelque chose à éviter au maximum car on a du mal à suivre le fil sur les différentes conditions et la valeur finale. Il faut privilégier les constantes pour que les valeurs soient plus facilement prévisibles.

Est-ce que l'exemple plus bas ne serait pas plus simple ?

Si je ne dis pas de bétises, pour `groupType === 'outing'` on n'a pas de `entourageType` ? Du coup on peut directement retourner quelque chose.

Ensuite, si c'est pas `groupeType outing`, là on a une couleur qui dépend de `entourageType`, et une icone qui dépend de `displayCategory`, c'est ça ?

```tsx
function FeedItemIcon(props: FeedItemIconProps) {
  const { feedItem } = props
  const { entourageType, displayCategory, groupType } = feedItem

  if (groupType === 'outing') {
    return (
      <Event
        style={{
          ...iconStyle,
          color: '#fff',
          backgroundColor: colors.main.grey,
        }}
      />
    )
  }

  const backgroundColors: Record<typeof entourageType, string> = {
    contribution: colors.main.primary,
    ask_for_help: colors.main.blue,
  }

  const iconProps = {
    style: {
      ...iconStyle,
      color: '#fff',
      backgroundColor: backgroundColors[entourageType],
    },
  }

  const IconComponent = feedItemCategoryIconMap[displayCategory] || feedItemCategoryIconMap.other

  return (
    <IconComponent {...iconProps} />
  )
}
```

Sinon rien à voir mais je trouve que ajouter `Map` n'apporte pas grand chose si ce n'est de la confusion, `feedItemCategoryIcons` au pluriel suffit je pense.

2021-01-19 21:49 UTC, GuillaumeJasmin commented on src/containers/Nav/Nav.tsx
> +import { useIsDesktop } from '../../styles'
```suggestion
import { useIsDesktop } from 'src/styles'
```

2021-01-19 21:49 UTC, GuillaumeJasmin commented on src/containers/Nav/NavNotificationBar.styles.ts
> + }
On n'est pas censé surcharger le style d'un bouton comme ça, normalement toutes les variantes doivent être dans le design system (et c'est tout la puissance d'un design system si on veut qu'il reste cohérent).

Ici du coup tu perds l'effet hover générique.
Donc 2 solutions possibles:
- on fait évoluer le design system avec un nouveau style de bouton
- on met un bouton existant

A mons sens, il vaudrait mieux le bouton avec la couleur secondary, car le texte blanc a coté d'un bouton aux contours blanc et avec lui même un texte blanc, je trouve que ça ne fait pas trop ressortir le bouton du reste.

![image](https://user-images.githubusercontent.com/3513444/105096329-30d16680-5aa7-11eb-9406-44d9b5cb4bce.png)
![image](https://user-images.githubusercontent.com/3513444/105096390-447ccd00-5aa7-11eb-8f5c-94f7699d7221.png)



Sinon, j'irai même plus loin, le bandeau orange attire beaucoup trop l'oeil, on dirait un bandeau d'alerte, et il capte toute l'attention.
Je pense qu'un bandeau plus sombre avec un bouton qui ressort un peu serait plus agréable et cohérent visuellement:

![image](https://user-images.githubusercontent.com/3513444/105097095-557a0e00-5aa8-11eb-9f04-cf4cca66ed10.png)

2021-01-19 21:49 UTC, GuillaumeJasmin commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +import { FeedDisplayCategory } from '../../../core/api'
```suggestion
import { FeedDisplayCategory } from 'src/core/api'
```

2021-01-20 09:19 UTC, emile-bex commented on src/containers/Nav/NavNotificationBar.styles.ts
> + }
T'as raison je vais modifier ça !

2021-01-20 21:19 UTC, GuillaumeJasmin approved these changes

2021-01-20 21:34 UTC, GuillaumeJasmin commented on src/containers/MapContainer/FeedList/FeedList.tsx
> +  }
Parfois il vaut mieux avoir un tout petit peu de duplication si ça améliore la compréhension, comme tu dis il faut trouver le juste milieu

2021-01-21 10:42 UTC, merged