[EN-2321] feat(POIs): created all use cases for the POIs
ReseauEntourage/entourage-webapp pull request #40
Opened 2021-02-02 23:42 UTC by emile-bex

2021-02-09 22:41 UTC, GuillaumeJasmin requested changes

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/containers/MapContainer/RightCards/POICards/POICards.tsx
> +  let card = isLoading ? <OverlayLoader /> : undefined
Pas de let. De plus, ça n'a pas à ce composant d'injecter un loader à l'intérieur d'un autre composant.
Je pense que c'est à `RightCard` d'afficher un loader si `card` est undefined

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/containers/Nav/NavItem.tsx
> +import * as NavStyles from './Nav.styles'
Pourquoi importer un autre fichier de style qui ne correspond pas au composant, et ne pas mettre le style dans le composant qui correspond ?

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/api/schema.ts
> +  DTOReopenEntourage, POIItem, POIDetailsItem,
```suggestion
  DTOReopenEntourage,
  POIItem,
  POIDetailsItem,
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.reducer.ts
> +    case PositionActionType.SET_POSITION: {
Normalement tu n'en as pas besoin ?

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.spec.ts
> +import { defaultPositionState } from '../position/position.reducer'
```suggestion
import { positionActions, PositionState, defaultPositionState } from '../position'
import { fakePositionData } from '../position/__mocks__'
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.spec.ts
> +    Then items should be fetched
```suggestion
    Given initial state
    When user init feed
      And user set position filters
    Then items should be fetched
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.spec.ts
> +    Then items should not be fetched
```suggestion
    Given initial state
    When user init feed
      And user set position filters
      And user cancel feed
      And user set a new position filters again
    Then items should be fetched only once
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.spec.ts
> +    expect(feedGateway.retrieveFeedItems).toHaveBeenCalledTimes(1)
Il faudrait en plus mettre une autre valeur à setPosition pour s'assurer qu'on trigger bien un changement de position

```suggestion
    store.dispatch(publicActions.cancel())

    store.dispatch(positionActions.setPosition(nextPosition))

    feedGateway.retrieveFeedItems.resolveDeferredValue()
    await store.waitForActionEnd()

    expect(feedGateway.retrieveFeedItems).toHaveBeenCalledTimes(1)
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/pois/TestPOIsGateway.ts
> +import { jestFn } from '../../utils/jestFn'
```suggestion
import { jestFn } from 'src/utils/jestFn'
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/pois/__mocks__.ts
> +}
```suggestion
export function createPOI(): POI {
  return {
    uuid: uniqStringId(),
    name: 'POI Name',
    longitude: 12,
    latitude: 14,
    address: 'Rue de la Tour Eiffel',
    phone: '',
    categoryId: 63,
    partnerId: null,
  }
}
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/pois/__mocks__.ts
> +  },
```suggestion
  pois: {
    abc: createPOI()
  },
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/pois/__mocks__.ts
> +}
```suggestion
export function createPOIDetails(): POIDetails {
  return {
    uuid: uniqStringId(),
    name: 'POI Name',
    longitude: 12,
    latitude: 14,
    address: 'Rue de la Tour Eiffel',
    phone: '',
    partnerId: null,
    description: '',
    categoryIds: [1],
    website: '',
    email: '',
    hours: '',
    languages: '',
    audience: '',
    source: 'entourage',
    sourceUrl: null,
  }
}
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/pois/pois.actions.ts
> +export type POIAction = ActionFromMapObject<typeof actions>
```suggestion
export type POIsAction = ActionFromMapObject<typeof actions>
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/pois/pois.reducer.ts
> +} from 'src/core/api'
```suggestion
import { POICategory, POISource } from 'src/core/api'
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/core/useCases/pois/pois.saga.ts
> +}
ça n'est pas utilisé (dans le fichier original non plus, j'ai oublié de l'enlever)

```suggestion
```

2021-02-09 22:41 UTC, GuillaumeJasmin commented on src/hooks/useCurrentRoute.ts
> +}
Toujours pas de let ;) 

```suggestion
interface CurrentRoute {
  currentRoute: Path;
  routeTitle: string;
}

export function useCurrentRoute(): CurrentRoute {
  const router = useRouter()

  if (router.pathname.includes('/actions')) {
    return {
      currentRoute: '/actions',
      routeTitle: routeTitles[currentRoute]  
    }
  }
  
  if (router.pathname.includes('/pois')) {
    return {
      currentRoute: '/pois',
      routeTitle: routeTitles[currentRoute],
    }
  }
  
  if (router.pathname.includes('/messages')) {
    return {
      currentRoute: '/messages',
      routeTitle: routeTitles[currentRoute],
    }
  }
  
  return {
    currentRoute: '/'
    routeTitle: routeTitles[currentRoute]
  }
}
```

2021-02-12 17:01 UTC, emile-bex commented on src/core/useCases/feed/feed.reducer.ts
> +    case PositionActionType.SET_POSITION: {
Il me semble qu'il le faut, pour que lors de la requête, on ne récupère pas la suite du feed mais bien le nouveau feed correspondant à la nouvelle position.

2021-02-12 17:04 UTC, emile-bex commented on src/constants/index.ts
> +  POI_MAX_DISTANCE: 5,
C'est la distance max de la valeur "distance" utilisé dans la requête. On le calcul à partir du zoom. mais ce n'est pas la même notion

2021-02-12 17:17 UTC, emile-bex commented on src/containers/MapContainer/RightCards/POICards/POICards.tsx
> +  let card = isLoading ? <OverlayLoader /> : undefined
En fait à cet endroit là, on ne regarde pas si `card` est _undefined_, mais on regarde si les détails du POI sont en train de charger. Si card est undefined on ne veut pas forcément afficher de loader. (avec les props il ne peux pas être null en plus). Je vais plutôt passer isLoading en props

2021-02-12 17:30 UTC, emile-bex commented on src/containers/MapContainer/RightCards/POICards/POICards.tsx
> +  let card = isLoading ? <OverlayLoader /> : undefined
Ca marcherai un truc comme ça ?

```
export function POICards() {
  const poi = useCurrentPOI()
  const poiDetailsFetching = useSelector(selectPOIDetailsIsFetching)
  const isLoading = useDelayLoadingNext(poiDetailsFetching)

  if (!poiDetailsFetching) {
    assertIsDefined(poi)
    return (
      <RightCard
        isLoading={isLoading}
        card={<POICard {...poi} />}
        href="/pois"
      />
    )
  }

  return (
    <RightCard
      isLoading={isLoading}
      href="/pois"
    />
  )
}
```

2021-02-12 18:50 UTC, emile-bex commented on src/components/POI/POI.styles.ts
> +  padding-right: 0 !important;
Il n'est pas pris en compte sinon malheureusement, j'ai déjà eu le cas :/

2021-02-14 18:23 UTC, loiclegoff commented on src/components/POI/POI.styles.ts
> +  padding-right: 0 !important;
Peut être voir quelle règle prend le dessus et voir pour que les deux cohabitent :)

2021-02-17 19:05 UTC, GuillaumeJasmin approved these changes

2021-02-18 10:11 UTC, merged