[EN-3269] Webapp Pouvoir Filtrer par type event/action ou autre système en fonction de la Refonte du Feed
ReseauEntourage/entourage-webapp pull request #42
Opened 2021-02-14 20:46 UTC by loiclegoff

2021-02-15 09:52 UTC, emile-bex commented on src/core/useCases/feed/feed.spec.ts
> +  it(`
Pour moi il y a plusieurs trucs à tester :
- Dans le cas par défaut (sans se soucier de l'appel à l'API), quand on change les filtres, il faut vérifier que le state a été mis à jour avec les valeurs
- Si le feed est activé, quand on change seulement les filtres du feed (sans se soucier de la position), il faut vérifier que la requête ai été appelé avec les valeurs
- MàJ le test : Si le feed est activé, on récupère bien les éléments
- MàJ le test : Si le feed n'est pas activé, rien ne se passe
- MàJ le test : Si le feed est annulé, rien ne se passe

Il faut ensuite mettre à jour tous les autres tests avec des valeurs par défaut pour les filtres de type (comme tu as fais)

2021-02-15 09:52 UTC, emile-bex commented on src/utils/types/Model.ts
> +
J'ai l'impression qu'aucune des autres valeurs de ce fichier n'est utilisé. On ne devrait pas les supprimer ?

2021-02-22 09:04 UTC, emile-bex commented on src/core/useCases/feed/feed.spec.ts
Je viens de penser à quelque chose d'autre (je ne sais pas trop si ça va dans les uses cases ou si ce sera purement côté UI) :
Il ne faudrait pas gérer un genre de **_debounce_** si chaque toggle d'un filtre va relancer la requête ? Histoire d'éviter le spam ?

2021-03-15 16:47 UTC, emile-bex commented on src/core/useCases/feed/feed.selectors.ts
> +export function selectIsActiveFilter(state: AppState, type: FilterEntourageType, category?: FilterFeedCategory) {
A voir avec @GuillaumeJasmin , mais je ne sais pas si ça se fait de passer des paramètres d'entrée à des sélecteurs ?
On peut peut-être faire ce teste là dans le composant directement ?

2021-03-15 18:38 UTC, GuillaumeJasmin commented on src/utils/types/Model.ts
> +
Oui complètement on peut supprimer, c'était un oubli du départ

2021-03-15 18:39 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.spec.ts
Bien vu, ou alors un apply manuel ? Car un debounce ça me parait compliqué, le timeout sera trop long

2021-03-15 18:53 UTC, GuillaumeJasmin requested changes

2021-03-15 18:53 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.spec.ts
> +`, async () => {
```suggestion
  it(`
    Given initial state
    When user init feed
      And user change the filter with type CONTRIBUTION
    Then store should be updated with new feed filters values
      And CONTRIBUTION filtrer should not be selected
      And retrieve items service should have been called with empty filter CONTRIBUTION
`, async () => {
```

2021-03-15 18:53 UTC, GuillaumeJasmin commented on src/core/useCases/feed/feed.actions.ts
> +function toggleFeedFilter(payload: { type: FilterEntourageType; category?: FilterFeedCategory;}) {
`setFeedFilter` me semble plus approprié, car c'est pas un simple toggle.

```suggestion
function setFeedFilter(payload: { type: FilterEntourageType; category?: FilterFeedCategory;}) {
```

2021-03-15 18:53 UTC, GuillaumeJasmin commented on src/core/useCases/feed/IFeedGateway.ts
> +}
Pense aux espaces 

```suggestion
}

```

2021-03-15 18:53 UTC, GuillaumeJasmin commented on src/containers/MapContainer/LeftLists/FeedFiltersSelector/SectionFilter/SectionFilter.tsx
> +export function SectionFilter(props: SectionFilterProps) {
```suggestion
}

export function SectionFilter(props: SectionFilterProps) {
```

2021-03-15 18:53 UTC, GuillaumeJasmin commented on src/containers/MapContainer/LeftLists/FeedFiltersSelector/SectionFilter/LineFilter.tsx
> +  const checked = selectIsActiveFilter(store.getState(), type, category)
```suggestion
  const dispatch = useDispatch()
  const checked = useSelector(state => selectIsActiveFilter(state, type, category))
```

2021-03-16 15:10 UTC, emile-bex commented on src/adapters/gateways/HTTPFeedGateway.ts
> +    const types = formatTypes(data.filters.types)
@loiclegoff je viens de voir, il ne faudrait pas mettre la logique en dehors de la Gateway (dans la saga par exemple) ?
Guillaume m'avait fait cette remarque une fois pour autre chose une fois.

2021-03-16 15:10 UTC, emile-bex commented on src/core/useCases/feed/IFeedGateway.ts
> +  types: FeedState['filters'];
Et ici du coup utiliser`types: ReturnType<typeof formatTypes>;`

2021-03-16 15:20 UTC, GuillaumeJasmin commented on src/adapters/gateways/HTTPFeedGateway.ts
> +    const types = formatTypes(data.filters.types)
En effet ! La gateway doit contenir le moins de logique possible, voire pas du tout

2021-03-16 17:47 UTC, emile-bex commented on src/containers/MapContainer/LeftLists/FeedFiltersSelector/SectionFilter/helper.ts
> +export const mapCategoriesToIcons: Record<FilterFeedCategory, IconType> = {
@loiclegoff il y a déjà un _map_ avec les icônes que j'avais fais dans le fichier `FeedItemIcon` que tu peux ré-utiliser je pense en utilisant ton _map_ dans `formatFeedFilterTypes.ts`

2021-03-16 17:47 UTC, emile-bex commented on src/i18n/fr.ts
> +      filters: {
Les labels existent déjà dans le fichier `texts` (les clefs sont juste en minuscule)

2021-03-17 08:07 UTC, loiclegoff commented on src/core/useCases/feed/feed.actions.ts
> +function toggleFeedFilter(payload: { type: FilterEntourageType; category?: FilterFeedCategory;}) {
C'est vrai mais je trouve qu'on est encore plus loin qu'un set ^^. Vu que je maj à l'opposé de l'état précedent. Mais so ça vous semble plus claire à vous deux, go!

2021-03-17 08:22 UTC, loiclegoff commented on src/adapters/gateways/HTTPFeedGateway.ts
> +    const types = formatTypes(data.filters.types)
C'est bogé, très bien vu :)

2021-03-17 08:23 UTC, loiclegoff commented on src/core/useCases/feed/IFeedGateway.ts
> +  types: FeedState['filters'];
j'aime pas trop mette une dépendence d'un helper, donc j'ai préféré `string` qui est le contrat de l'API

2021-03-17 08:24 UTC, loiclegoff commented on src/adapters/gateways/HTTPFeedGateway.ts
> +    const types = formatTypes(data.filters.types)
Je m'interroge quand même si on ne doit pas avoir un couch d'adapter entre gateway et useCase ?

2021-03-17 08:30 UTC, emile-bex commented on src/core/useCases/feed/feed.actions.ts
> +function toggleFeedFilter(payload: { type: FilterEntourageType; category?: FilterFeedCategory;}) {
Moi je suis plutôt pour le `toggle` également, vu qu'on l'active ou désactive avec la même action

2021-03-17 08:33 UTC, emile-bex commented on src/core/useCases/feed/IFeedGateway.ts
> +  types: FeedState['filters'];
Ca me va c'est vrai que c'est la Gateway qui doit imposer le type car c'est elle qui sait ce dont elle a besoin

2021-03-17 08:36 UTC, emile-bex commented on src/core/useCases/feed/feed.spec.ts
Surtout @loiclegoff , comment c'est fait maintenant, si jamais on clique sur un autre filtre alors qu'une requête est en cours, la deuxième requête ne va pas être envoyé, mais le filtre va être toggle, du coup il y aura une dissonance entre les filtres et les données

2021-03-17 08:37 UTC, emile-bex commented on src/core/useCases/feed/feed.actions.ts
> +function toggleFeedFilter(payload: { type: FilterEntourageType; category?: FilterFeedCategory;}) {
Quitte à faire 2 actions, une pour le `type` et une pour la `category`?

2021-03-17 10:26 UTC, emile-bex commented on src/containers/MapContainer/LeftLists/FeedFiltersSelector/SectionFilter/SectionFilter.tsx
> +      <LineFilter
Est-ce qu'ici tu ne peux pas rendre le rendu dynamic ? Avec un `Object.keys(FilterFeedCategory).map()`

2021-03-17 12:32 UTC, loiclegoff commented on src/containers/MapContainer/LeftLists/LeftList.tsx
> +        {isFeedPage && <FeedFiltersSelector />}
done ;)

2021-03-17 12:33 UTC, loiclegoff commented on src/containers/MapContainer/LeftLists/FeedFiltersSelector/SectionFilter/helper.ts
> +export const mapCategoriesToIcons: Record<FilterFeedCategory, IconType> = {
j'ai trouvé le mapping :)

2021-03-17 12:34 UTC, loiclegoff commented on src/i18n/fr.ts
> +      filters: {
c'est bon mais j'ai fait un move!

2021-03-17 12:39 UTC, loiclegoff commented on src/containers/MapContainer/LeftLists/FeedFiltersSelector/SectionFilter/SectionFilter.tsx
> +      <LineFilter
je vais partir sur: `[
          FilterFeedCategory.SOCIAL,
          FilterFeedCategory.MAT_HELP,
          FilterFeedCategory.RESOURCE,
          FilterFeedCategory.OTHER,
        ]` pour avoir un ordre déterminé

2021-03-17 12:46 UTC, loiclegoff commented on src/core/useCases/feed/feed.spec.ts
J'ai l'impression qu'un debounce est gérer par material et on a donc pas vraiment d'état incompatible. Les fetch on l'air de se faire bien.

2021-03-17 16:43 UTC, merged