[EN-3634] feat(map): manual fetching
ReseauEntourage/entourage-webapp pull request #71
Opened 2021-04-28 15:57 UTC by emile-bex

2021-05-05 21:59 UTC, GuillaumeJasmin requested changes

2021-05-05 21:59 UTC, GuillaumeJasmin commented on src/core/useCases/pois/poi.spec.ts
> +          distance: constants.POI_DISTANCE,
Même chose ici, ce n'est pas dans les specs, et pourquoi on met la valeur par défaut ?

2021-05-06 08:25 UTC, emile-bex commented on src/core/useCases/location/location.saga.ts
> +      yield put(actions.setMapPosition({
Les tests ont été rajouté dans le dernier commit que j'ai fais 😉

2021-05-06 08:28 UTC, emile-bex commented on src/core/useCases/feed/feed.saga.ts
>        if (feedIsIdle) {
De même, les tests ont été rajouté dans le dernier commit :)

2021-05-06 09:21 UTC, merged